### ISSUE TITLE
Interstitial Take Time To Load :

### ISSUE THREAD

**Issue by tauseeq-grace** [UmairOye/Google-Admob#1]
See the attached Screenshot of your code:

![screenshot](https://github.com/UmairOye/AdMobAllAdsImplementation/assets/144904817/a15b28cb-9ed0-415d-a2fc-81b21f38cf14)

**Comment by UmairOye** [comment]
thank you tauseeq for pointing it out, am a little bit busy in some other stuff, will set it soon.
